{
    'name': 'Property Management - Manage Rent/Lease, Sales | Property Rental Contract Management| Property Sales Contract Management',
    'version': '19.0.1.1',
    'summary': """
        Odoo Property Management Software for Real Estate, Property Sale Lease and Rental Management App, 
        Real Estate and Property Management ERP Solution, Advanced Property Rental Management System in Odoo, 
        Best Property Management Software for Landlords and Agents, Real Estate Property Management Software for Small Landlords, 
        Rental Property Management Software for Odoo ERP, Odoo Real Estate Property Management System for Rental and Sales, 
        Complete Property Maintenance and Facility Management in Odoo, Odoo Real Estate Management App for Property Rental and Sale, 
        Real Estate CRM and Property Management Software for Agents, Property Management System for Short-Term and Long-Term Rentals, 
        Odoo Property Lease Management and Tenant Tracking, Real Estate ERP Software with Property Sales and Rental Features, Odoo App for Property, 
        Building and Tenant Management, Real Estate CRM Software for Property Agents in Odoo, All-in-One Property Management Suite for Rental and Sales, 
        Odoo Property Maintenance Management Software for Real Estate, Property and Facility Management System using Odoo ERP, 
        Odoo Real Estate App for Managing Properties, Tenants and Leases, Best Odoo Property Management App for Landlords and Companies, 
        Real Estate and Rental Management Software built on Odoo 19, 
        Odoo Property Management App for Lease, Rent and Sale, Property Maintenance and Work Order Management in Odoo, 
        Real Estate CRM and Property Management Portal in Odoo, Odoo ERP App for Property and Building Management, 
        Real Estate Management System for Developers and Agencies, Odoo Rental Property Management Software for Landlords, 
        Best Odoo Real Estate and Rental Management Solution, Odoo Property Management and Real Estate CRM for Brokers, 
        Real Estate and Rental ERP App for Property Managers, Property Management Portal for Real Estate Companies in Odoo, 
        Odoo App for Rental Property and Tenant Management, Property and Facility Management Software with Odoo ERP, R
        eal Estate Lease and Rent Management System for Odoo 18, Property Management and CRM Integration in Odoo ERP, 
        Real Estate Property Sale and Rental Automation with Odoo, Odoo App for Real Estate Developers and Property Agents, Best Odoo App for Property, 
        Lease and Maintenance, Real Estate Property Management Module for Odoo 19, Property and Asset Management ERP Solution using Odoo, 
        Odoo Property Management System for Rental, Sales and Lease, Real Estate CRM and Rental Management Suite for Odoo, 
        Property Manager Dashboard App for Odoo ERP, Real Estate Property Listing and Rental Software for Odoo, Odoo Property and Facility Maintenance ERP Module, 
        Real Estate and Rental Property Software for Landlords, Property Management ERP for Agents, Tenants and Owners, 
        Advanced Odoo Real Estate Property Management Suite, Odoo CRM Integrated Property Management System for Real Estate.
    """,
    'description': """
        Property Management Suite for Rental, Sales & Lease, Odoo Property Management ERP, Real Estate Management System for Odoo, 
        Property Rental and Lease Management App, Real Estate ERP Suite for Property Companies, Smart Property Management Portal in Odoo, 
        Property & Tenant Management Solution, Real Estate Sales and Lease ERP System, Odoo Real Estate Suite for Rent and Sales, 
        Property Lease Management with Accounting, Rental Property Manager for Odoo ERP, Real Estate and Rental Management Suite, 
        Odoo Property Manager App for Real Estate, Property Management and Tenant Tracking ERP, Rental & Lease Management System in Odoo, 
        Real Estate CRM and Property Suite for Odoo, Property Accounting and Rental Management App, Odoo Real Estate Management Portal, 
        Real Estate Property Suite for Rentals and Lease, Property Rental Management System for Odoo, Property Manager ERP for Tenants and Owners, 
        Odoo Real Estate Management Suite Pro, Property Management App for Odoo Enterprise, Smart Real Estate Lease and Rental Portal, 
        Property Management ERP for Real Estate Agents, Odoo Property Rental and Lease Manager, Real Estate and Tenant Management ERP, 
        Property Management Dashboard for Odoo ERP, Real Estate Rental Management Software for Odoo, Property Lease and Contract Management System, 
        Rental Property ERP for Real Estate Business, Odoo Property Manager with Lease & Sales, Real Estate and Rental ERP Suite for Odoo, 
        Property Lease & Rent Management App, Real Estate Property Management System, Odoo Real Estate Portal with Tenant Management, 
        Property Management Suite for Real Estate Firms, Real Estate CRM and Lease Management ERP, Property and Rental Management Solution for Odoo, 
        Odoo Real Estate ERP for Property Companies, Property Management & Accounting Suite, Real Estate Property ERP with Tenant Portal, 
        Property Lease & Rental Automation in Odoo, Odoo Property Management Software Solution, Property Manager ERP for Rentals & Sales, 
        Real Estate and Lease Accounting ERP App, Property Rental ERP with Tenant & Contract, Smart Property Management Software for Odoo,
         Odoo ERP for Real Estate and Property Firms, Real Estate Suite for Rent, Sales & Lease, Property Management Portal | Real Estate ERP
    """,
    'author': "Tectise",
    'website': 'https://www.tectise.com',
    'category': 'industries',
    'depends': ['base', 'mail', 'product', 'contacts', 'hr', 'crm', 'sale', 'maintenance'],
    'data': [
        'data/property_contract_seq.xml',
        'data/contract_settlement_seq.xml',
        'data/product_product_data.xml',
        'data/ir_cron.xml',
        'data/ir_sequence.xml',
        'reports/contract_settlement_print_report.xml',
        'security/ir.model.access.csv',
        'security/property_security.xml',
        'wizard/unit_creation_wizard.xml',
        'wizard/property_invoice_wizard.xml',
        'wizard/property_bill_wizard.xml',
        'wizard/account_payment_register_views.xml',
        'wizard/contract_settlement_wizard.xml',
        'wizard/eoi_payment_wizard.xml',
        'wizard/so_booking_wizard.xml',
        'wizard/so_booking_payment_wizard.xml',
        'wizard/registration_acknowledgement_wizard.xml',
        'wizard/so_invoice_wizard_views.xml',
        'wizard/confirm_property_wizard_view.xml',
        'views/so_payment_plan.xml',
        'views/account_payment_views.xml',
        'views/res_config_settings.xml',
        'views/property_property_views.xml',
        'views/property_unit_views.xml',
        'views/property_contract_views.xml',
        'views/contract_settlement_views.xml',
        'views/property_config_views.xml',
        'views/product_product_views.xml',
        'views/res_partner_views.xml',
        'views/property_invoice.xml',
        'views/account_move_views.xml',
        # 'views/property_kyc_views.xml',
        'views/so_booking_view.xml',
        'views/maintenance_request_views.xml',
        'views/crm_property_visit_views.xml',
        'views/property_menu.xml',
        'views/property_unit_utility.xml',
        'views/sale_order.xml',
        'views/crm_lead_views.xml',
    ],
    'assets': {
    },
    'price': 100.00,
    'currency': "EUR",
    'license': 'OPL-1',
    "images": ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
