{
    'name': 'Employee Leave Summary Report | HR Time Off Report | Time Off Summary Report',
    'version': '17.0.1.0.0',
    'category': 'Human Resources',
    'summary': """
        employee leave report, employee leave summary, hr leave report, hr time off report, 
        employee absence report, leave analytics, time off analytics, hr absence dashboard, 
        employee leave dashboard, leave management report, hr leave management, time off management, 
        employee vacation report, paid leave report, sick leave tracking, leave balance report, 
        employee leave history, leave usage analytics, leave consumption report, time off tracker, 
        hr leave tracker, odoo leave report, odoo hr leave, odoo time off, odoo absence report, 
        odoo leave analytics, odoo hr dashboard, employee attendance and leave, hr attendance report, 
        employee time off dashboard, leave summary dashboard, hr metrics report, 
        workforce leave analytics, employee availability report, leave planning report, 
        leave forecasting, leave utilization report, employee absence trends, time off trends, 
        leave insights, hr workforce analytics, employee leave kpi, hr leave kpi, time off kpi, 
        leave performance report, leave compliance report, hr compliance tracking, leave audit report, 
        hr reporting tool, employee hr analytics, leave workflow report, leave approval tracking, 
        employee leave approval report, hr productivity report, workforce management report, 
        employee engagement metrics, absence management system, leave management system, 
        hr management software, hr reporting module, employee leave module, time off management software, hr dashboard for odoo, 
        odoo hr module, odoo employee leave, odoo workforce management, odoo hr analytics, 
        leave data analysis, time off data analysis, employee leave statistics, hr leave statistics, 
        leave report for managers, time off report for hr, absence report for hr, employee leave summary app, 
        hr leave summary tool, odoo leave summary, odoo time off tracker, odoo hr reporting, 
        employee absence management, leave and attendance report, hr absence analytics
    """,
    'description': """
    employee leave tracking software, hr time off management, employee vacation planner, 
    leave request analytics, staff absence tracking, workforce availability report, 
    hr leave utilization, employee time off planning, leave entitlement report, hr leave forecasting, 
    staff leave calendar, employee holiday tracking, hr vacation dashboard, paid time off analytics, 
    pto tracking report, leave liability report, employee time off balance, hr absence planning, 
    leave quota management, workforce absence report, staff leave utilization, hr leave trends, 
    employee vacation analytics, leave accrual report, hr leave compliance, time off approval report,
     employee holiday analytics, leave request dashboard, hr absence metrics, workforce leave planning,
      staff time off tracker, employee leave monitoring, hr time off insights, leave schedule report,
       employee vacation summary, hr holiday management, paid leave dashboard, employee pto report, 
       leave cycle report, staff availability planning, hr leave control, employee time off statistics,
        absence trend analysis, leave workflow analytics, staff leave summary, hr workforce availability, 
        employee leave optimization, time off efficiency report
    """,
    'author': 'Tectise',
    'website': 'https://www.tectise.com',
    'depends': ['hr', 'hr_holidays'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/leave_summary_wizard_views.xml',
        'views/menu_views.xml',
    ],
    'external_dependencies': {
        'python': ['xlsxwriter'],
    },
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'OPL-1',
    'price': 10.00,
    'currency': 'USD',
}
