from . import property_amenities
from . import property_facilities
from . import property_category
from . import property_city
from . import property_connectivity
from . import property_duration
from . import property_furnish_type
from . import property_specification
from . import property_tags
from . import property_type
from . import property_unit
from . import property_utitlity
from . import property_property
from . import property_project
from . import res_partner
from . import hr_employee
from . import property_contract
from . import property_invoice
from . import contract_settlement
from . import account_move
from . import sale_order
from . import crm_lead
from . import maintenance_request
from . import property_unit_utility
from . import res_config_settings
from . import property_unit_type
from . import property_payment
from . import account_payment
from . import so_installment_line
from . import so_payment_plan
from . import so_booking
from . import crm_property_visit
from . import crm_property_visit_expense_line
